import "bootstrap/dist/css/bootstrap.min.css"; // Import bootstrap CSS
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import styles from "./layout.module.css"

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fr">
      <body className={`${geistSans.variable} ${geistMono.variable} d-flex flex-column`}>
      <div className={styles.principal}>
          <Header /> {/* Inclusion de l'entête */}
          <main className={`${styles.bob} container-fluid flex-grow-1 min-vh-100`}>{/* le flex grow a 1 permet de garder le foter en bas de la page, il faut que le body soit en d-flex et flex column */}
            {children} {/* Affiche le contenu enfant passé au composant Layout */}
          </main>
          <Footer /> {/* Inclusion du pied de page */}
        </div>
      </body>
    </html>
  );
}
